# Base image
FROM runpod/base:0.4.2-cuda11.8.0

ADD . .

RUN python3.11 -m pip install --upgrade pip && \
  python3.11 -m pip install --upgrade -r requirements.txt --no-cache-dir && \
  rm requirements.txt


COPY src/endpoints/kandinsky_22/builder.py builder.py
RUN python3.11 builder.py && \
  rm builder.py

CMD python3.11 -u src/endpoints/kandinsky_22/handler.py